config/routes.rb
Rails.application.routes.draw do

  mount ActionCable.server => "/cable"

  authenticated :user do
    root to: "home#main", as: :authenticated_root
  end

  unauthenticated do
    root to: "home#index", as: :unauthenticated_root
  end

  devise_for :users

  resources :programs do
    resources :workouts do
      resources :exercises
    end
  end

  resources :chats

  resources :sessions do
    resources :movements
    resources :likes, only: [ :create, :destroy ]
    resources :comments
  end

  resources :friends, only: [ :create, :index, :update, :destroy ]

  root to: "home#index"

  get "profile", to: "home#profile", as: "profile"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :session
end

app/models/exercise.rb
class Exercise < ApplicationRecord
  belongs_to :workout
  has_many :movements
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: "User"
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :session
end

app/models/movement.rb
class Movement < ApplicationRecord
  belongs_to :session
  belongs_to :exercise, optional: true
end

app/models/program.rb
class Program < ApplicationRecord
  has_many :workouts, dependent: :destroy
  accepts_nested_attributes_for :workouts
  belongs_to :user
end

app/models/session.rb
class Session < ApplicationRecord
  has_many :movements, dependent: :destroy
  accepts_nested_attributes_for :movements
  belongs_to :user
  belongs_to :workout, optional: true

  has_many :likes
  has_many :likers, through: :likes, source: :user

  has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :programs
  has_many :sessions

  has_many :friendships
  has_many :friends, through: :friendships, source: :friend

  has_many :inverse_friendships, class_name: "Friendship", foreign_key: "friend_id"
  has_many :inverse_friends, through: :inverse_friendships, source: :user

  has_many :likes
  has_many :liked_posts, through: :likes, source: :session

  has_many :comments, dependent: :destroy
end

app/models/workout.rb
class Workout < ApplicationRecord
  belongs_to :program
  has_many :exercises, dependent: :destroy
  has_many :sessions
  accepts_nested_attributes_for :exercises
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  def create
    friend_user = User.find(params[:friend])
    current_user.friendships.create(friend: friend_user, status: 0)
  end

  def index
    if params[:query]
      @friends = User.where(email: params[:query])
    end

      @requests = current_user.inverse_friendships.where(status: 0)
      @currentfriends = (
      current_user.friendships.where(status: 1).map(&:friend) +
      current_user.inverse_friendships.where(status: 1).map(&:user)
      ).uniq

    @users = User.all
  end

  def update
    friendship = Friendship.find(params[:id])
    if friendship.status == 0
      friendship.update(status: 1)
    else
      friendship.update(status: 0)
    end
  end

  def destroy
    friend = User.find_by(params[:id])
    friend = User.find(params[:id])  # the user you're trying to unfriend
    friendship = Friendship.find_by(user: current_user, friend: friend) ||
                 Friendship.find_by(user: friend, friend: current_user)
    friendship.destroy!
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def home
  end

  def main
    @currentfriends = (
      current_user.friendships.where(status: 1).map(&:friend) +
      current_user.inverse_friendships.where(status: 1).map(&:user)
      ).uniq

      @allsessions = @currentfriends.flat_map(&:sessions) + current_user.sessions
      @sessions = @allsessions.sort_by(&:date)
  end

  def profile
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chat_helper.rb
module ChatHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/movements_helper.rb
module MovementsHelper
end

app/helpers/programs_helper.rb
module ProgramsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/workouts_helper.rb
module WorkoutsHelper
end

app/views/friends/index.html.erb
<div class="card m-1 m-lg-5">
  <div class="card-header">
    <h1>Friends</h1>
  </div>
  <div class="card-body">
  <%= form_with url: friends_path, method: :get, local: true do |f| %>
    <div class="mb-3">
      <%= f.label :query, "Find Friends", class: "form-label" %>
      <%= f.text_field :query, class: "form-control", placeholder: "Search by name or email" %>
    </div>
    <%= f.submit "Search", class: "btn btn-primary" %>
  <% end %>

  <div class="mt-2">
    <% if @friends %>
      <h1>Search</h1>
        <% @friends.each do |f| %>
          <div class="row">
            <%=  f.email %> 
            <% if @currentfriends.include?(f)  %>
              <p>Already Friends</p>

            <% elsif current_user.friendships.exists?(friend: f, status: 0) %>
              <p>Request Sent!</p>

            <% else %>
              <%= button_to "Add Friend", friends_path(friend: f.id), method: :post, class:"btn btn-outline-success" %>
            <% end %>
          </div>
        <% end %>
    <% end %>
  </div>

<div class="mt-2">
  <h1>Requests</h1>
  <% if @requests.present? %>
    <% @requests.each do |r| %>
    <div class="row">
      <div class="col-4">
        <%=  r.user.email %> 
      </div>
      <div class="col-4">
        <%= button_to "Accept", friend_path(r.id), method: :patch%>
      </div>
      <div class="col-4">
        <%= button_to "Reject", friend_path(r.id), method: :delete, class:"btn btn-outline-danger", data: {turbo: false}%>
      </div>
    </div>
    <% end %>
  <% else %>
  <p>None...</p>
  <% end %>
</div>

<div class="mt-3">
  <h1> Current Friends </h1>
<% if @currentfriends %>
    <% @currentfriends.each do |cf| %>
    <div class="row">
      <div class="col-6">
        <%=  cf.email %> 
      </div>
      <div class="col-6">
        <%= button_to "Remove Friend", friend_path(cf.id), method: :delete, class:"btn btn-outline-danger", data: {turbo: false}%>
      </div>   
   </div>
    <% end %>
<% else %>
<p>None...</p>
<% end %>
</div>

</div>
</div>



<% @users.each do |u| %>
  <div>
    email: <%= u.email %>
      <% u.friendships.each do |f| %>
        user1: <%= f.user.email %>
      friend1: <%= f.friend.email %>  <%= f.status %>
      <% end %>
      <% u.inverse_friendships.each do |f| %>
      user2: <%= f.user.email %>
      friend2: <%= f.friend.email %> <%= f.status %>
      <% end %>
  </div>
<% end %>