config/routes.rb
Rails.application.routes.draw do

  mount ActionCable.server => "/cable"

  authenticated :user do
    root to: "home#main", as: :authenticated_root
  end

  unauthenticated do
    root to: "home#index", as: :unauthenticated_root
  end

  devise_for :users

  resources :programs do
    resources :workouts do
      resources :exercises
    end
  end

  resources :chats

  resources :sessions do
    resources :movements
    resources :likes, only: [ :create, :destroy ]
    resources :comments
  end

  resources :friends, only: [ :create, :index, :update, :destroy ]

  root to: "home#index"

  get "profile", to: "home#profile", as: "profile"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :session
end

app/models/exercise.rb
class Exercise < ApplicationRecord
  belongs_to :workout
  has_many :movements
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: "User"
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :session
end

app/models/movement.rb
class Movement < ApplicationRecord
  belongs_to :session
  belongs_to :exercise, optional: true
end

app/models/program.rb
class Program < ApplicationRecord
  has_many :workouts, dependent: :destroy
  accepts_nested_attributes_for :workouts
  belongs_to :user
end

app/models/session.rb
class Session < ApplicationRecord
  has_many :movements, dependent: :destroy
  accepts_nested_attributes_for :movements
  belongs_to :user
  belongs_to :workout, optional: true

  has_many :likes
  has_many :likers, through: :likes, source: :user

  has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :programs
  has_many :sessions

  has_many :friendships
  has_many :friends, through: :friendships, source: :friend

  has_many :inverse_friendships, class_name: "Friendship", foreign_key: "friend_id"
  has_many :inverse_friends, through: :inverse_friendships, source: :user

  has_many :likes
  has_many :liked_posts, through: :likes, source: :session

  has_many :comments, dependent: :destroy
end

app/models/workout.rb
class Workout < ApplicationRecord
  belongs_to :program
  has_many :exercises, dependent: :destroy
  has_many :sessions
  accepts_nested_attributes_for :exercises
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def home
  end

  def main
    @currentfriends = (
      current_user.friendships.where(status: 1).map(&:friend) +
      current_user.inverse_friendships.where(status: 1).map(&:user)
      ).uniq

      @allsessions = @currentfriends.flat_map(&:sessions) + current_user.sessions
      @sessions = @allsessions.sort_by(&:date)
  end

  def profile
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def create
    @session = Session.find(params[:session_id])
    current_user.likes.create(session: @session)
  end

  def destroy
    @session = Session.find(params[:session_id])
    @like = current_user.likes.find_by(session: @session)
    @like.destroy!
  end

end

app/controllers/programs_controller.rb
class ProgramsController < ApplicationController
  before_action :set_program, only: %i[ show edit update destroy ]

  # GET /programs or /programs.json
  def index
    @programs = current_user.programs.all
  end

  # GET /programs/1 or /programs/1.json
  def show
  end

  # GET /programs/new
  def new
    @program = current_user.programs.new
    workout = @program.workouts.build
    workout.exercises.build
  end

  # GET /programs/1/edit
  def edit
  end

  # POST /programs or /programs.json
  def create
    @program = current_user.programs.new(program_params)

    respond_to do |format|
      if @program.save
        format.html { redirect_to @program, notice: "Program was successfully created." }
        format.json { render :show, status: :created, location: @program }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @program.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /programs/1 or /programs/1.json
  def update
    respond_to do |format|
      if @program.update(program_params)
        format.html { redirect_to @program, notice: "Program was successfully updated." }
        format.json { render :show, status: :ok, location: @program }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @program.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /programs/1 or /programs/1.json
  def destroy
    @program.destroy!

    respond_to do |format|
      format.html { redirect_to programs_path, status: :see_other, notice: "Program was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_program
      @program = current_user.programs.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def program_params
      params.require(:program).permit(:name, :desc, :user_id, workouts_attributes: [ :id, :name, :desc, :program_id, exercises_attributes: [ :id, :name, :sets, :reps, :workout_id ] ])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chat_helper.rb
module ChatHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/movements_helper.rb
module MovementsHelper
end

app/helpers/programs_helper.rb
module ProgramsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/workouts_helper.rb
module WorkoutsHelper
end

app/views/programs/_form.html.erb
<div data-controller="programcreate" class="m-5">
<%= form_with(model: program) do |form| %>
  <% if program.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(program.errors.count, "error") %> prohibited this program from being saved:</h2>
      <ul>
        <% program.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <!-- Program name & description -->
  <div class="mb-3">
    <%= form.label :name, style: "display: block;" %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="mb-4">
    <%= form.label :desc, style: "display: block;" %>
    <%= form.textarea :desc, class: "form-control" %>
  </div>

  <!-- Workouts section -->
  <div class="workoutbutton">
    <div data-programcreate-target="workoutcontainer" class="workoutcontainer">
      <input data-programcreate-target="workoutindex" class="workoutindex" type="hidden" value="1">

      <%= form.fields_for :workouts do |work| %>
        <input class="workoutnumber" type="hidden" value="0">

        <div class="border rounded p-3 mb-4">
          <h4>Workout</h4>
          <div class="row mb-3">
            <div class="col-md-6">
              <%= work.label :name, style: "display: block;" %>
              <%= work.text_field :name, class: "form-control" %>
            </div>
            <div class="col-md-6">
              <%= work.label :desc, style: "display: block;" %>
              <%= work.textarea :desc, class: "form-control" %>
            </div>
          </div>

          <div class="exercisebutton">
            <div class="exercisecontainer border p-2 mb-3 rounded">
              <%= work.fields_for :exercises do |ex| %>
                <input class="exerciseindex" type="hidden" value="1">
                <button type="button" class="btn btn-sm btn-outline-secondary" data-action="click->programcreate#addexercise">Add Exercise</button>
                <div class="exercise">
                  <div class="row">
                    <div class="col-md-3">
                      <%= ex.label :name, style: "display: block;" %>
                      <%= ex.text_field :name, class: "form-control" %>
                    </div>
                    <div class="col-md-3">
                      <%= ex.label :sets, style: "display: block;" %>
                      <%= ex.number_field :sets, class: "form-control" %>
                    </div>
                    <div class="col-md-3">
                      <%= ex.label :reps, style: "display: block;" %>
                      <%= ex.text_field :reps, class: "form-control" %>
                    </div>

                    <div class="col-md-3">
                      <%= ex.label :action, style: "display: block;" %>
                      <button type="button" data-action="click->programcreate#removeexercise" class="btn btn-secondary">Remove</button>
                    </div>
                  
                  </div>
                </div>
              <% end %>

            </div>
          </div>
        </div>
      <% end %>
    </div>

    <!-- Add workout button -->
    <button type="button" class="btn btn-outline-primary mb-3" data-action="click->programcreate#addworkout">Add Workout</button>
  </div>

  <div>
    <%= form.submit "Save Program", class: "btn btn-success" %>
  </div>
<% end %>

<template data-programcreate-target="workouttemplate">
  <div class="workoutcontainer border rounded p-3 my-3">
    <input class="workoutnumber" type="hidden">
    
    <div class="row mb-3">
      <div class="col-md-6">
        <label for="program_workouts_attributes_PROGRAM_INDEX_name" class="form-label">Workout Name</label>
        <input type="text" class="form-control" name="program[workouts_attributes][PROGRAM_INDEX][name]" id="program_workouts_attributes_PROGRAM_INDEX_name">
      </div>
      <div class="col-md-6">
        <label for="program_workouts_attributes_PROGRAM_INDEX_desc" class="form-label">Description</label>
        <textarea class="form-control" name="program[workouts_attributes][PROGRAM_INDEX][desc]" id="program_workouts_attributes_PROGRAM_INDEX_desc"></textarea>
      </div>
    </div>

    <div class="exercisecontainer">
      <input type="hidden" class="exerciseindex" value="1">
      <button type="button" class="btn btn-outline-primary btn-sm" data-action="click->programcreate#addexercise">Add Exercise</button>
      <!-- First exercise -->
      <div class="exercise row mb-2">
        <div class="col-md-3">
          <label class="form-label" for="program_workouts_attributes_PROGRAM_INDEX_exercises_attributes_0_name">Exercise Name</label>
          <input type="text" class="form-control" name="program[workouts_attributes][PROGRAM_INDEX][exercises_attributes][0][name]" id="program_workouts_attributes_PROGRAM_INDEX_exercises_attributes_0_name">
        </div>
        <div class="col-md-3">
          <label class="form-label" for="program_workouts_attributes_PROGRAM_INDEX_exercises_attributes_0_sets">Sets</label>
          <input type="number" class="form-control" name="program[workouts_attributes][PROGRAM_INDEX][exercises_attributes][0][sets]" id="program_workouts_attributes_PROGRAM_INDEX_exercises_attributes_0_sets">
        </div>
        <div class="col-md-3">
          <label class="form-label" for="program_workouts_attributes_PROGRAM_INDEX_exercises_attributes_0_reps">Reps</label>
          <input type="text" class="form-control" name="program[workouts_attributes][PROGRAM_INDEX][exercises_attributes][0][reps]" id="program_workouts_attributes_PROGRAM_INDEX_exercises_attributes_0_reps">
        </div>

        <div class="col-md-3 d-flex flex-column">
          <label class="form-label">Action</label>
          <button type="button" data-action="click->programcreate#removeexercise" style="width:80px;" class="btn btn-secondary">Remove</button>
        </div>

      </div>
    </div>
    <button type="button" data-action="click->programcreate#removeworkout" class="btn btn-secondary">Delete Workout</button>
  </div>
</template>

<template data-programcreate-target="exercisetemplate">
  <div class="exercise row mb-2">
    <div class="col-md-3">
      <label class="form-label">Exercise Name</label>
      <input type="text" class="form-control" name="program[workouts_attributes][PROGRAM_INDEX][exercises_attributes][EXERCISE_INDEX][name]">
    </div>

    <div class="col-md-3">
      <label class="form-label">Sets</label>
      <input type="number" class="form-control" name="program[workouts_attributes][PROGRAM_INDEX][exercises_attributes][EXERCISE_INDEX][sets]">
    </div>

    <div class="col-md-3">
      <label class="form-label">Reps</label>
      <input type="text" class="form-control" name="program[workouts_attributes][PROGRAM_INDEX][exercises_attributes][EXERCISE_INDEX][reps]">
    </div>

    <div class="col-md-3 d-flex flex-column">
      <label class="form-label">Action</label>
      <button type="button" style="width:80px;" data-action="click->programcreate#removeexercise" class="btn btn-secondary col-md-3 d-flex flex-column">Remove</button>
    </div>
  </div>
</template>

</div>

app/views/programs/_formedit.html.erb
<div data-controller="programcreate" class="m-5">
<%= form_with(model: program) do |form| %>
  <% if program.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(program.errors.count, "error") %> prohibited this program from being saved:</h2>
      <ul>
        <% program.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <!-- Program name & description -->
  <div class="mb-3">
    <%= form.label :name, style: "display: block;" %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="mb-4">
    <%= form.label :desc, style: "display: block;" %>
    <%= form.textarea :desc, class: "form-control" %>
  </div>

  <!-- Workouts section -->
  <div class="workoutbutton">
    <div data-programcreate-target="workoutcontainer" class="workoutcontainer">
      <input data-programcreate-target="workoutindex" class="workoutindex" type="hidden" value="1">

      <%= form.fields_for :workouts do |work| %>
        <input class="workoutnumber" type="hidden" value="0">

        <div class="border rounded p-3 mb-4">
          <h4>Workout</h4>
          <div class="row mb-3">
            <div class="col-md-6">
              <%= work.label :name, style: "display: block;" %>
              <%= work.text_field :name, class: "form-control" %>
            </div>
            <div class="col-md-6">
              <%= work.label :desc, style: "display: block;" %>
              <%= work.textarea :desc, class: "form-control" %>
            </div>
          </div>

          <div class="exercisebutton">
            <div class="exercisecontainer border p-2 mb-3 rounded">
              <%= work.fields_for :exercises do |ex| %>
                <input class="exerciseindex" type="hidden" value="1">
                <div class="exercise">
                  <div class="row">
                    <div class="col-4">
                      <%= ex.label :name, style: "display: block;" %>
                      <%= ex.text_field :name, class: "form-control" %>
                    </div>
                    <div class="col-4">
                      <%= ex.label :sets, style: "display: block;" %>
                      <%= ex.number_field :sets, class: "form-control" %>
                    </div>
                    <div class="col-4">
                      <%= ex.label :reps, style: "display: block;" %>
                      <%= ex.text_field :reps, class: "form-control" %>
                    </div>

                  </div>
                </div>
              <% end %>

            </div>
          </div>
        </div>
      <% end %>
    </div>

    <!-- Add workout button -->
  </div>

  <div>
    <%= form.submit "Save Program", class: "btn btn-success" %>
  </div>
<% end %>

<template data-programcreate-target="workouttemplate">
  <div class="workoutcontainer border rounded p-3 my-3">
    <input class="workoutnumber" type="hidden">
    
    <div class="row mb-3">
      <div class="col-md-6">
        <label for="program_workouts_attributes_PROGRAM_INDEX_name" class="form-label">Workout Name</label>
        <input type="text" class="form-control" name="program[workouts_attributes][PROGRAM_INDEX][name]" id="program_workouts_attributes_PROGRAM_INDEX_name">
      </div>
      <div class="col-md-6">
        <label for="program_workouts_attributes_PROGRAM_INDEX_desc" class="form-label">Description</label>
        <textarea class="form-control" name="program[workouts_attributes][PROGRAM_INDEX][desc]" id="program_workouts_attributes_PROGRAM_INDEX_desc"></textarea>
      </div>
    </div>

    <div class="exercisecontainer">
      <input type="hidden" class="exerciseindex" value="1">
      <!-- First exercise -->
      <div class="exercise row mb-2">
        <div class="col-4">
          <label class="form-label" for="program_workouts_attributes_PROGRAM_INDEX_exercises_attributes_0_name">Exercise Name</label>
          <input type="text" class="form-control" name="program[workouts_attributes][PROGRAM_INDEX][exercises_attributes][0][name]" id="program_workouts_attributes_PROGRAM_INDEX_exercises_attributes_0_name">
        </div>
        <div class="col-4">
          <label class="form-label" for="program_workouts_attributes_PROGRAM_INDEX_exercises_attributes_0_sets">Sets</label>
          <input type="number" class="form-control" name="program[workouts_attributes][PROGRAM_INDEX][exercises_attributes][0][sets]" id="program_workouts_attributes_PROGRAM_INDEX_exercises_attributes_0_sets">
        </div>
        <div class="col-4">
          <label class="form-label" for="program_workouts_attributes_PROGRAM_INDEX_exercises_attributes_0_reps">Reps</label>
          <input type="text" class="form-control" name="program[workouts_attributes][PROGRAM_INDEX][exercises_attributes][0][reps]" id="program_workouts_attributes_PROGRAM_INDEX_exercises_attributes_0_reps">
        </div>


      </div>
    </div>
  </div>
</template>

<template data-programcreate-target="exercisetemplate">
  <div class="exercise row mb-2">
    <div class="col-4">
      <label class="form-label">Exercise Name</label>
      <input type="text" class="form-control" name="program[workouts_attributes][PROGRAM_INDEX][exercises_attributes][EXERCISE_INDEX][name]">
    </div>

    <div class="col-4">
      <label class="form-label">Sets</label>
      <input type="number" class="form-control" name="program[workouts_attributes][PROGRAM_INDEX][exercises_attributes][EXERCISE_INDEX][sets]">
    </div>

    <div class="col-4">
      <label class="form-label">Reps</label>
      <input type="text" class="form-control" name="program[workouts_attributes][PROGRAM_INDEX][exercises_attributes][EXERCISE_INDEX][reps]">
    </div>

  </div>
</template>

</div>

app/views/programs/_program.html.erb
<div id="<%= dom_id program %>" class="container my-4">
  <div class="mb-4">
    <h3 class="mb-2">Program Details</h3>
    <div class="row">
      <div class="col-md-4">
        <strong>Name:</strong>
        <p><%= program.name %></p>
      </div>
      <div class="col-md-8">
        <strong>Description:</strong>
        <p><%= program.desc %></p>
      </div>
    </div>
  </div>
  <div id="workouts">
  <% program.workouts.each_with_index do |workout, i| %>
    <%= turbo_frame_tag "workout_#{workout.id}" do %>
      <div class="border rounded p-3 mb-4">
        <div class="row">
          <div class="col-6">
            <strong>Name:</strong>
            <p><%= workout.name %></p>
          </div>
          <div class="col-6">
            <strong>Description:</strong>
            <p><%= workout.desc %></p>
          </div>
        </div>

        <% if workout.exercises.any? %>
          <div class="mt-3">
            <h6>Exercises</h6>
            <div class="row fw-bold border-bottom pb-1 mb-2">
              <div class="col-3">Name</div>
              <div class="col-3">Sets</div>
              <div class="col-3">Reps</div>
              <div class="col-3"><%= link_to "Add", new_program_workout_exercise_path(program, workout), data: {turbo_frame:"new_#{workout.id}"}, class:"btn btn-outline-primary"%></div>
            </div>
            <div id="workout<%=workout.id%>">
            <% workout.exercises.each do |exercise| %>
              <%= turbo_frame_tag "exercise_#{exercise.id}" do %>
                <div class="row mb-2">
                  <div class="col-3"><%= exercise.name %></div>
                  <div class="col-3"><%= exercise.sets %></div>
                  <div class="col-3"><%= exercise.reps %></div>
                  <div class="col-3"><%= button_to "X", program_workout_exercise_path(program, workout, exercise), class:"btn btn-outline-secondary", method: :delete %></div>
                </div>
              <% end %>
            <% end %>
            </div>

              <%= turbo_frame_tag "new_#{workout.id}" %>
          </div>
        <% end %>
          <div class="card-footer d-flex justify-content-evenly">
            <%= link_to "Log Session", new_session_path(workout_id: workout), class:"btn btn-outline-primary my-2", data: {turbo: false} %>
            <%= button_to "Remove Workout", program_workout_path(program, workout), class:"btn btn-outline-danger my-2", method: :delete %>
          </div>
    </div>

  <% end %>
  <% end %>
  </div>
  <div class="d-flex justify-content-center">
  <%= link_to "Add Workout", new_program_workout_path(program), class:"btn btn-outline-primary", data: {turbo_frame: "hi"}%>
  </div>
  <%= turbo_frame_tag "hi" %>

</div>

app/views/programs/_programname.html.erb
      <div class="col-4">
        <strong>Name:</strong>
        <p><%= program.name %></p>
      </div>
      <div class="col-4">
        <strong>Description:</strong>
        <p><%= program.desc %></p>
      </div>

  

app/views/programs/edit.html.erb
<% content_for :title, "Editing program" %>

<h1>Editing program</h1>

<%= render "formedit", program: @program %>

<br>

<div>
  <%= link_to "Show this program", @program %> |
  <%= link_to "Back to programs", programs_path %>
</div>

app/views/programs/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Programs" %>
<div class="card m-1 m-lg-5">
  <div class="card-header">
    <h1>Programs</h1>
  </div>

  <div id="programs" class="card-body">
    <% @programs.each do |program| %>
    <div class="row">
      <%= render "programname", program: program %>
      <div class="col-4">
      <%= link_to "Show this program", program, class:"btn btn-outline-secondary" %>
      </div>
    </div>
    <% end %>
  </div>

</div>
<div class="m-2">
  <%= link_to "New program", new_program_path, class:"btn btn-outline-primary" %>
</div>

app/views/programs/new.html.erb
<% content_for :title, "New program" %>

<h1>New program</h1>

<%= render "form", program: @program %>

<br>

<div>
  <%= link_to "Back to programs", programs_path %>
</div>

app/views/programs/show.html.erb
<% if notice %>
  <div class="alert alert-success">
    <%= notice %>
  </div>
<% end %>

<%= render @program %>

<div class="mt-4 d-flex gap-3 flex-wrap justify-content-center my-5">
  <%= link_to "Edit Program", edit_program_path(@program), class: "btn btn-outline-warning" %>
  <%= link_to "Back to Programs", programs_path, class: "btn btn-outline-secondary" %>
  <%= button_to "Delete Program", @program, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-outline-danger" %>
</div>