config/routes.rb
Rails.application.routes.draw do

  mount ActionCable.server => "/cable"

  authenticated :user do
    root to: "home#main", as: :authenticated_root
  end

  unauthenticated do
    root to: "home#index", as: :unauthenticated_root
  end

  devise_for :users

  resources :programs do
    resources :workouts do
      resources :exercises
    end
  end

  resources :chats

  resources :sessions do
    resources :movements
    resources :likes, only: [ :create, :destroy ]
    resources :comments
  end

  resources :friends, only: [ :create, :index, :update, :destroy ]

  root to: "home#index"

  get "profile", to: "home#profile", as: "profile"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :session
end

app/models/exercise.rb
class Exercise < ApplicationRecord
  belongs_to :workout
  has_many :movements
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: "User"
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :session
end

app/models/movement.rb
class Movement < ApplicationRecord
  belongs_to :session
  belongs_to :exercise, optional: true
end

app/models/program.rb
class Program < ApplicationRecord
  has_many :workouts, dependent: :destroy
  accepts_nested_attributes_for :workouts
  belongs_to :user
end

app/models/session.rb
class Session < ApplicationRecord
  has_many :movements, dependent: :destroy
  accepts_nested_attributes_for :movements
  belongs_to :user
  belongs_to :workout, optional: true

  has_many :likes
  has_many :likers, through: :likes, source: :user

  has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :programs
  has_many :sessions

  has_many :friendships
  has_many :friends, through: :friendships, source: :friend

  has_many :inverse_friendships, class_name: "Friendship", foreign_key: "friend_id"
  has_many :inverse_friends, through: :inverse_friendships, source: :user

  has_many :likes
  has_many :liked_posts, through: :likes, source: :session

  has_many :comments, dependent: :destroy
end

app/models/workout.rb
class Workout < ApplicationRecord
  belongs_to :program
  has_many :exercises, dependent: :destroy
  has_many :sessions
  accepts_nested_attributes_for :exercises
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def home
  end

  def main
    @currentfriends = (
      current_user.friendships.where(status: 1).map(&:friend) +
      current_user.inverse_friendships.where(status: 1).map(&:user)
      ).uniq

      @allsessions = @currentfriends.flat_map(&:sessions) + current_user.sessions
      @sessions = @allsessions.sort_by(&:date)
  end

  def profile
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def create
    @session = Session.find(params[:session_id])
    current_user.likes.create(session: @session)
  end

  def destroy
    @session = Session.find(params[:session_id])
    @like = current_user.likes.find_by(session: @session)
    @like.destroy!
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chat_helper.rb
module ChatHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/movements_helper.rb
module MovementsHelper
end

app/helpers/programs_helper.rb
module ProgramsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/workouts_helper.rb
module WorkoutsHelper
end

app/views/chats/index.html.erb
<h1>CHAT FEATURE POSSIBLE!</h1>

<div id="messages"></div>

<form id="chat-form">
  <input type="text" id="chat-input" placeholder="Type message..." autocomplete="off">
  <input type="submit" value="Send">
</form>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary p-3">
  <div class="container-fluid">
    <%= link_to "ULFT ", root_path, class:"navbar-brand"%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <% if user_signed_in? %>
        <%= link_to "Home", root_path, class:"nav-link"%>
        <%= link_to "Profile", profile_path, class:"nav-link"%>
        <%= link_to "Add Friends", friends_path, class:"nav-link"%>
        <%= link_to "Settings 👤", edit_user_registration_path, class:"nav-link"%>
        <%= link_to "Log Out", destroy_user_session_path, data:{turbo_method: :delete}, class:"nav-link"%>
        <% else %>
        <%= link_to "Log In", new_user_session_path, class:"nav-link"%>
        <%= link_to "Sign Up", new_user_registration_path, class:"nav-link"%>
        <% end %>
      </div>
    </div>
  </div>
</nav>

app/views/home/index.html.erb
<div class="width:auto">
    <%= button_to "Log In", new_user_session_path, class:"btn btn-primary"%>
</div>

app/views/home/main.html.erb
        <div class="m-2 d-flex justify-content-evenly">
            <%= link_to "Your Programs", programs_path, class:"btn btn-outline-primary"%>
            <%= link_to "Your Sessions", sessions_path, class:"btn btn-outline-success"%>
        </div>

<div class="card m-1 m-md-5">
    <div class="card-header">
        <h1>Sessions</h1>
    </div>
    <div class="card-body">
        <% if @sessions.present?%>
            <% @sessions.each do |s|%>
                <div class="card">
                        <div class="card-header">
                            <%= s.user.email %>
                        </div>
                    <div class="card-body">
                        <div>
                            <h1><%= s.name %></h1>
                        </div>
                        <div class="row"> 
                            <% s.movements.each do |m| %>
                            <div class="cold-12 col-md-4">
                                <h3><%= m.name %></h3>
                                <p>"<%= m&.notes || "no notes"%>"</p>
                                <% weightreps = JSON.parse(m.work)%>
                                <div>Sets: <%= weightreps.count %></div>
                                <% weightreps.each_with_index do |set| %>
                                 <div>
                                    <%= set["weight"]%> kg
                                    reps: <%= set["rep"]%>
                                 </div>
                                <% end %>
                            </div>
                            <% end %>
                        </div>

                        <div class="d-flex mt-2">
                            <div class="mt-3">like: <%= s.likes.count%></div>

                            <% if s.likes.find_by(user: current_user) %>
                                <% like = s.likes.find_by(user: current_user) %>
                                <%= button_to "remove like", session_like_path(s, like), method: :delete, class:"btn btn-secondary m-2"%>
                            <% else %>
                                <%= button_to "like", session_likes_path(s), class:"btn btn-primary m-2"%>
                            <% end %>
                        </div>

                        <%= link_to "Show this session", s, class:"btn  btn-secondary mx-2" %>


                        <% s.likes.each do |l| %>
                            liker: <%= l.user.email %>
                        <% end %>
                    </div>
                </div>
            <% end %>
        <% end %>
    </div>
<div>

app/views/home/profile.html.erb
<h1>Profile</h1>

<%= link_to "Your Programs", programs_path, class:"btn btn-outline-primary"%>
<%= link_to "Your Sessions", sessions_path, class:"btn btn-outline-success"%>